// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  accountId: __t.u64().name("account_id"),
  symbol: __t.string(),
  targetPrice: __t.f64().name("target_price"),
  alertType: __t.string().name("alert_type"),
  active: __t.bool(),
  createdAt: __t.timestamp().name("created_at"),
  triggeredAt: __t.option(__t.timestamp()).name("triggered_at"),
});
