// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  symbol: __t.string().primaryKey(),
  name: __t.string(),
  exchange: __t.string(),
  currency: __t.string(),
  price: __t.f64(),
  previousClose: __t.f64().name("previous_close"),
  change: __t.f64(),
  changePercent: __t.f64().name("change_percent"),
  dayHigh: __t.f64().name("day_high"),
  dayLow: __t.f64().name("day_low"),
  volume: __t.f64(),
  lastUpdated: __t.timestamp().name("last_updated"),
});
