// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Alert = __t.object("Alert", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
  targetPrice: __t.f64(),
  alertType: __t.string(),
  active: __t.bool(),
  createdAt: __t.timestamp(),
  triggeredAt: __t.option(__t.timestamp()),
});
export type Alert = __Infer<typeof Alert>;

export const BotConfig = __t.object("BotConfig", {
  key: __t.string(),
  value: __t.string(),
});
export type BotConfig = __Infer<typeof BotConfig>;

export const PriceFetchSchedule = __t.object("PriceFetchSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type PriceFetchSchedule = __Infer<typeof PriceFetchSchedule>;

export const StockPrice = __t.object("StockPrice", {
  symbol: __t.string(),
  name: __t.string(),
  exchange: __t.string(),
  currency: __t.string(),
  price: __t.f64(),
  previousClose: __t.f64(),
  change: __t.f64(),
  changePercent: __t.f64(),
  dayHigh: __t.f64(),
  dayLow: __t.f64(),
  volume: __t.f64(),
  lastUpdated: __t.timestamp(),
});
export type StockPrice = __Infer<typeof StockPrice>;

export const UserProfile = __t.object("UserProfile", {
  identity: __t.identity(),
  phone: __t.string(),
  telegramChatId: __t.option(__t.string()),
  registeredAt: __t.timestamp(),
});
export type UserProfile = __Infer<typeof UserProfile>;

export const WatchlistItem = __t.object("WatchlistItem", {
  id: __t.u64(),
  owner: __t.identity(),
  symbol: __t.string(),
});
export type WatchlistItem = __Infer<typeof WatchlistItem>;

